from .db import db
from .notice import Notice
from .oa import OA
from .permission_group import PermissionGroup
from .permission_node import PermissionNode
from .role import Teacher,Student
from .school_class import SchoolClass
from .subject import Subject
from .time_slot import TimeSlotTable,Activity
from .transaction_detail import TransactionDetail
from .user import User